name: GraalPy-ocicli
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    #runs-on: self-hosted
    env:
      OCI_CLI_USER: ${{ secrets.OCI_CLI_USER }}
      OCI_CLI_TENANCY: ${{ secrets.OCI_CLI_TENANCY }}
      OCI_CLI_FINGERPRINT: ${{ secrets.OCI_CLI_FINGERPRINT }}
      OCI_CLI_KEY_CONTENT: ${{ secrets.OCI_CLI_KEY_CONTENT }}
      OCI_CLI_REGION: ${{ secrets.OCI_CLI_REGION }}
      OCI_FUNC_COMPT: ${{ secrets.OCI_FUNC_COMPT }}
    steps:
      - name: List functions
        uses: oracle-actions/run-oci-cli-command@v1.2.0
        id: list-functions
        with:
          command: 'oci fn application list -c ${{ secrets.OCI_FUNC_COMPT }}'
          silent: false
      - name: Log into OCIR
        uses: oracle-actions/login-ocir@v1.2.1
        id: login-ocir
        with:
          auth_token: ${{ secrets.OCI_AUTH_TOKEN }}
