name: GraalPy-ocicli
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    #runs-on: self-hosted
    env:
      OCI_FUNC_COMPT: ${{ secrets.OCI_FUNC_COMPT }}
    steps:
      - name: List functions
        uses: oracle-actions/run-oci-cli-command@v1.2.0
        id: list-functions
        with:
          command: ' oci fn application list -c ${{ secrets.OCI_FUNC_COMPT }}'
    
