name: GraalPy
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Setup GraalPy
      uses: actions/setup-python@v5
      with:
        python-version: graalpy # or graalpy24.0 to pin a version
