name: GraalPy
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Setup GraalPy
      uses: actions/setup-python@v5
      with:
        python-version: graalpy24.0
    - name: Set env
      run: |
        graalpy -m venv .
        source ./bin/activate
        graalpy -m standalone native \
        --output graalpyfunction \
        --module func.py \
        --venv .
