name: GraalPy
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    #runs-on: self-hosted
    env:
      OCI_FUNC_COMPT: ${{ secrets.OCI_FUNC_COMPT }}
    steps:
    #
    #- name: List functions
    #  run: |
    #    oci fn application list -c ${{ secrets.OCI_FUNC_COMPT }} --auth instance_principal
    #
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Setup GraalVM
      uses: graalvm/setup-graalvm@v1
      with:
        java-version: '21'      # See 'Options' section below for all supported versions
        distribution: 'graalvm' # See 'Options' section below for all available distributions
        #github-token: ${{ secrets.GITHUB_TOKEN }}
    - name: Versions
      run: |
        echo "GRAALVM_HOME: $GRAALVM_HOME"
        echo "JAVA_HOME: $JAVA_HOME"
        java --version
        native-image --version
    - name: Setup GraalPy
      uses: actions/setup-python@v5
      with:
        python-version: graalpy24.0
    - name: Set env
      run: |
        graalpy -m venv .
    - name: Activate env
      run: |
        source ./bin/activate
    - name: Cat func
      run: |
        cat src/func.py
    - name: Run GraalPy
      run: |
        graalpy -m standalone native \
        --output graalpyfunction \
        --module src/func.py \
        --venv .
