name: GraalPy
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    #runs-on: self-hosted
    env:
      OCI_CLI_USER: ${{ secrets.OCI_CLI_USER }}
      OCI_CLI_TENANCY: ${{ secrets.OCI_CLI_TENANCY }}
      OCI_CLI_FINGERPRINT: ${{ secrets.OCI_CLI_FINGERPRINT }}
      OCI_CLI_KEY_CONTENT: ${{ secrets.OCI_CLI_KEY_CONTENT }}
      OCI_CLI_REGION: ${{ secrets.OCI_CLI_REGION }}
      OCI_FUNC_COMPT: ${{ secrets.OCI_FUNC_COMPT }}
      OCI_FUNC_OCID: ${{ secrets.OCI_FUNC_OCID }}
    steps:
    - name: Set current date as env variable
      run: echo "NOW=$(date +'%Y-%m-%d-%H-%M-%S')" >> $GITHUB_ENV
    - name: Echo current date
      run: echo ${{ env.NOW }}
    - name: Checkout code
      uses: actions/checkout@v4
    - name: List functions
      uses: oracle-actions/run-oci-cli-command@v1.2.0
      with:
        command: "oci fn function list --application-id ${{ secrets.OCI_APP_OCID }}"
        silent: false
    - name: Setup GraalVM
      uses: graalvm/setup-graalvm@v1
      with:
        java-version: '21'      # See 'Options' section below for all supported versions
        distribution: 'graalvm' # See 'Options' section below for all available distributions
        #github-token: ${{ secrets.GITHUB_TOKEN }}
    - name: Versions
      run: |
        echo "GRAALVM_HOME: $GRAALVM_HOME"
        echo "JAVA_HOME: $JAVA_HOME"
        java --version
        native-image --version
    - name: Setup GraalPy
      uses: actions/setup-python@v5
      with:
        python-version: graalpy24.0
    - name: Set GraalPy env
      run: |
        graalpy -m venv .
    - name: Activate GraalPy env
      run: |
        source ./bin/activate
        ./bin/pip install -r src/requirements.txt
    - name: Run GraalPy
      run: |
        graalpy -m standalone native \
        --output graalpyfunction \
        --module src/func.py \
        --venv .
    - name: Log into OCIR
      uses: oracle-actions/login-ocir@v1.2.1
      with:
        auth_token: ${{ secrets.OCI_AUTH_TOKEN }}
    - name: Build and Push graalpyfunction
      run: |
        docker build -t fra.ocir.io/frsxwtjslf35/graalpyfunction:${{ env.NOW }} .
        docker push fra.ocir.io/frsxwtjslf35/graalpyfunction:${{ env.NOW }}
    - name: Create function
      uses: oracle-actions/run-oci-cli-command@v1.2.0
      with:
        command: "oci fn function update --function-id ${{ secrets.OCI_FUNC_OCID }} --image fra.ocir.io/frsxwtjslf35/graalpyfunction:${{ env.NOW }}"
        silent: false
        